### ISSUE TITLE
More esbuild options!

### ISSUE THREAD

**Issue by Aslemammad** [Aslemammad/vite-plugin-cloudflare#1]
Feedbacks are welcome :)

**Comment by TorbjornHoltmon** [comment]
Great package! Exactly what I was looking for.
I would like to have source maps.

**Comment by Aslemammad** [comment]
Thank you!
Can you send a PR for that?

**Comment by Aslemammad** [comment]
@TorbjornHoltmon Now you can have source maps both in dev/build with `--sourcemap` flag!

**Comment by Aslemammad** [comment]
I'd like to add more options as you wish!

**Comment by PuruVJ** [comment]
I think loaders would be good to expose 🙂

**Comment by PuruVJ** [comment]
I think same as what esbuild has.

I recommend keeping anything you add to be as close to esbuild. Would make it easier for folks, I think :)
