### ISSUE TITLE
ERROR: Invalid option in build() call: "jsxSideEffects" Vite v4

### ISSUE THREAD

**Issue by alexturpin** [Aslemammad/vite-plugin-cloudflare#15]
Hey folks,

Great plugin! Been trying to get it to work with my custom Vite development server without much success so far. While trying to figure that out however, I upgraded to the latest version of Vite (4.0) and realized that this breaks the plugin in a different way:

```
error when starting dev server:
Error: Build failed with 1 error:
/Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in build() call: "jsxSideEffects"
    at failureErrorWithLog (/Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:1143:18
    at /Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:1138:9
    at /Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/alexturpin/src/vpc-test/node_modules/vite-plugin-cloudflare/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
```

Also if anyone has successfully integrated this with a custom dev server, any tips? Even on Vite 3. Getting this error:
```
ReferenceError: Cannot access 'seenIds' before initialization
    at Object.delayDepsOptimizerUntil (file:///Users/alexturpin/src/vpc-test/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:41492:55)
    at doTransform (file:///Users/alexturpin/src/vpc-test/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36846:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Aslemammad** [comment]
Hey Alex, Sure, I'll work on it.

**Comment by Aslemammad** [comment]
I updated one of the examples (basic) to vite@4 and it works without no problem. So it'd be good to try again (or the latest version), anyways, if it still does not work, I'd_ like to see a reproduction!

Same for the custom server, I'd like to see a reproduction.

**Comment by alexturpin** [comment]
@Aslemammad thank you so much for taking the time 🙏 

After looking into it some more, the v4 problem seems to be related to using the Vite React plugin too, hence why it doesn't show up in the basic example. Here's a repro: https://github.com/alexturpin/vpc-test

Here's a repro for a custom server, back with Vite v3: https://github.com/alexturpin/vpc-test/tree/custom-server

**Comment by Aslemammad** [comment]
Thank you so much Alex, I'll take a look soon.

**Comment by alexturpin** [comment]
@Aslemammad you rock!

**Comment by Aslemammad** [comment]
Hey @alexturpin, Fixed in v0.3.0! Could you please check if it's fixed? Thank you so much.

**Comment by alexturpin** [comment]
Absolutely will try next week!

**Comment by Aslemammad** [comment]
Sure, thanks.

**Comment by alexturpin** [comment]
@Aslemammad now getting `TypeError: esbuild.context is not a function` 🤔 

Updated my example here: https://github.com/alexturpin/vpc-test

**Comment by alexturpin** [comment]
Looks like maybe esbuild was moved from dependencies to devDependencies?

**Comment by Aslemammad** [comment]
I guess you need to update your esbuild version, and if possible, share the stack.

**Comment by alexturpin** [comment]
Sorry, I'm not sure I understand. Do I have to install my own esbuild peer dependency? It was my understanding that vite-plugin-cloudflare ran esbuild under the hood. Can you elaborate on what information I can provide about the stack? It's a simple vite app https://github.com/alexturpin/vpc-test

**Comment by Aslemammad** [comment]
sure, I meant the error stack! let me run the app again and see, because last time it worked for me.

**Comment by Aslemammad** [comment]
And in the server.ts file (for custom server), you also need to add this line of code, so the middlewares get applied.

```
  app.use(vite.middlewares)
```

**Comment by Aslemammad** [comment]
I've been able to reproduce the error, and it is because Vite's using an older version of esbuild, so to fix the error, you need to update esbuild:
```
npm add -D esbuild@latest
```

**Comment by alexturpin** [comment]
Ah yes sorry my bad, I had put the full error in my repo README but not here 😅 Installing esbuild ourselves does seem to fix it, thank you. 🙏 

Shouldn't esbuild be a dependency of vite-plugin-cloudflare in this case, just like in 0.2.0? If it makes its own use of it, and requires a specific version as well. Or at the very least a peer dependency? It seems to me this would happen to new users on a fresh install without too much warning otherwise.

**Comment by Aslemammad** [comment]
sure, i'll add this to the docs.

**Comment by alexturpin** [comment]
Thanks for all the hard work on this plugin, it makes for a very slick setup

**Comment by Aslemammad** [comment]
Sure, feel free to create more issues and suggestions, it'd help so much.
