### ISSUE TITLE
No HTML is rendered even when using the basic example

### ISSUE THREAD

**Issue by Kyiro** [Aslemammad/vite-plugin-cloudflare#16]
I'm trying to use the example and publish it with wrangler but it doesn't work, all it renders is an empty html page. Using `vite dev` works though

**Comment by Aslemammad** [comment]
Hey Kyiro, I'm going to check it out. Thanks for the report.

**Comment by Aslemammad** [comment]
I've updated the basic example, I guess now it works.
let me know.

**Comment by Kyiro** [comment]
Yeah, it works. Thank you for fixing it
