### ISSUE TITLE
Cannot read properties of undefined (reading 'fd')

### ISSUE THREAD

**Issue by altryne** [Aslemammad/vite-plugin-cloudflare#17]
I think it's a polyfill issue? 
I'm getting 
```
<script>:78872
      return "colors" in exports14.inspectOpts ? Boolean(exports14.inspectOpts.colors) : tty.isatty(process.stderr.fd);
                                                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'fd')

```

I would love to use this, and I'm playing around with the telegraf package, alas, the webpack build suggested by the author of telegraf cloudflare is 5seconds each build. but this package fails on the above `process.stderr.fd`

**Comment by Aslemammad** [comment]
Thank you so much, Do you have any reproduction?

**Comment by altryne** [comment]
Yeah, this repo basically: 
https://github.com/Tsuk1ko/cfworker-telegraf-template
Trying to replace webpack in there with vite and this plugin, and that repo includes telegraf.js which is a telegram library, and it shows the above error

**Comment by Aslemammad** [comment]
@altryne #19 solves the issue with custom polyfills (use the `process/browser` package), but it creates a new issue:
```
Error: Some functionality, such as asynchronous I/O (fetch, Cache API, KV), timeouts (setTimeout, s
etInterval), and generating random values (crypto.getRandomValues, crypto.subtle.generateKey), can 
only be performed while handling a request.

```
Which I belive can be solves by another polyfill? or even import the `telegraf` package into the handler instead of the outside of it.
Let me know if it works so I merge it.

**Comment by altryne** [comment]
whoah! Thanks, I'll take a look when I get to the telegram bot again, thank you!

**Comment by Aslemammad** [comment]
That'd be great, let me know so I release this.

**Comment by Aslemammad** [comment]
@altryne Any updates?

**Comment by Aslemammad** [comment]
Feel free to re-open if this feature does not work!
