### ISSUE TITLE
Universal plugin

### ISSUE THREAD

**Issue by Aslemammad** [Aslemammad/vite-plugin-cloudflare#3]
Blocked by https://github.com/vitejs/vite/issues/5936

**Comment by Aslemammad** [comment]
I saw @brillout's ideas around deployment plugins! I'd like to start working on taking out vite-plugin-cloudflare from its cli form and make it a vite plugin!
I'd like to hear suggestions and how we can get into that level (since AFAIK some agreed on using vite's buildEnd hook)!

CC @brillout

**Comment by brillout** [comment]
Yes the `writeBundle()` trick can be used to trigger the esbuild build at the end of `$ vite build`. With `enforce: post`, this could also work together with vite-plugin-ssr. To be tested.

As for `$ vite deploy`, that requires a Vite PR.
