### ISSUE TITLE
The .env file not loaded when using Miniflare 2

### ISSUE THREAD

**Issue by Bryanoxx** [Aslemammad/vite-plugin-cloudflare#8]
Hello !

I love this plugin and I think I just found a bug with the new version of Miniflare : I don't have any environment variables.

I checked a little bit and that's part of the [breaking change of the v2](https://github.com/cloudflare/miniflare/releases/tag/v2.0.0#:~:text=When%20using%20the%20API) : 
> When using the API, wrangler.toml, package.json and .env are no longer automatically loaded from their default locations.

So I suppose we just need to add the options that they are showing in the "breaking change" in this part of the code, and that would resolve the bug : https://github.com/Aslemammad/vite-plugin-cloudflare/blob/main/packages/vite-plugin-cloudflare/src/cli.ts#L70-L73

Thank you for this great plugin again ! 🔥

**Comment by Aslemammad** [comment]
Hello, How are you doing? Sorry for not seeing this issue! I don't know what the problem with GitHub notifs is.
What do you think the name should be? you got any suggestions?

And thank you for using this plugin; I'm happy.

**Comment by Bryanoxx** [comment]
Hello !

I'm not sure to understand you're question, you would like me to submit you names but I dont know names of what :/

Because I was just talking about the breaking change with Miniflare v2 so I'm a bit lost here ahah

Thank you and have a good day !

**Comment by Aslemammad** [comment]
Sure, I'll work on that soon! no need to confuse yourself, I'm going to take it :smile:
